springfox:
 title: 'FINT SSE Adapter Skeleton'
 version: '@version@'

fint:
 provider:
  adapter:
   organizations: hfk.no
   sse-endpoint: "https://api.felleskomponent.no/administrasjon/organisasjon/provider/sse/%s"
   status-endpoint: "https://api.felleskomponent.no/administrasjon/organisasjon/provider/status"
   response-endpoint: "https://api.felleskomponent.no/administrasjon/organisasjon/provider/response"
bluegarden:
  org-endpoint:
  employee-endpoint:
  username:
  password:
  employer:
  orgunitid:
  source-company:
  source-system:
  source-user:
  source-employer: