
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package no.fint.provider.bluegarden.soap;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T12:04:58.018+01:00
 * Generated source version: 3.1.9
 * 
 */

@WebService(
                      serviceName = "BasicHttpBinding_IOrgStructureServiceQSService",
                      portName = "BasicHttpBinding_IOrgStructureServiceQSPort",
                      targetNamespace = "http://bluegarden.no/organisation/structure/wsdl/v31",
                      /* wsdlLocation = "file:src/main/resources/schema/OrgStructureBA.wsdl" ,*/
                      endpointInterface = "no.bluegarden.IOrgStructureService")

public class BasicHttpBinding_IOrgStructureServiceQSPortImpl implements IOrgStructureService {

    private static final Logger LOG = Logger.getLogger(BasicHttpBinding_IOrgStructureServiceQSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see no.bluegarden.IOrgStructureService#getOrgUnit(no.bluegarden.GetOrgUnitRequest getOrgUnitRequest, no.bluegarden.BSBHeaderType bsbHeader)*
     */
    public GetOrgUnitResponse getOrgUnit(GetOrgUnitRequest getOrgUnitRequest, BSBHeaderType bsbHeader) {
        LOG.info("Executing operation getOrgUnit");
        System.out.println(getOrgUnitRequest);
        System.out.println(bsbHeader);
        try {
            GetOrgUnitResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see no.bluegarden.IOrgStructureService#getOrgList(no.bluegarden.GetOrgListRequest getOrgListRequest, no.bluegarden.BSBHeaderType bsbHeader)*
     */
    public GetOrgListResponse getOrgList(GetOrgListRequest getOrgListRequest, BSBHeaderType bsbHeader) {
        LOG.info("Executing operation getOrgList");
        System.out.println(getOrgListRequest);
        System.out.println(bsbHeader);
        try {
            GetOrgListResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
