
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package no.fint.provider.bluegarden.soap;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T12:04:57.413+01:00
 * Generated source version: 3.1.9
 * 
 */

@WebService(
                      serviceName = "GetAnsattListSOAPQSService",
                      portName = "GetAnsattListSOAPQSPort",
                      targetNamespace = "http://ansattlist.bluegarden.no/service/v3_1/wsdl",
                      /*wsdlLocation = "file:src/main/resources/schema/GetAnsattListBA.wsdl",*/
                      endpointInterface = "no.bluegarden.GetAnsattList")

public class GetAnsattListSOAPQSPortImpl implements GetAnsattList {

    private static final Logger LOG = Logger.getLogger(GetAnsattListSOAPQSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see no.bluegarden.GetAnsattList#getAnsattList(no.bluegarden.GetAnsattListRequestMessageType getAnsattListRequestMessage, no.bluegarden.BSBHeaderType bsbHeader)*
     */
    public GetAnsattListResultMessageType getAnsattList(GetAnsattListRequestMessageType getAnsattListRequestMessage, BSBHeaderType bsbHeader) {
        LOG.info("Executing operation getAnsattList");
        System.out.println(getAnsattListRequestMessage);
        System.out.println(bsbHeader);
        try {
            GetAnsattListResultMessageType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
