package no.fint.provider.bluegarden.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T12:04:57.472+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://ansattlist.bluegarden.no/service/v3_1/wsdl", name = "GetAnsattList")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetAnsattList {

    @WebMethod(operationName = "GetAnsattList", action = "GetAnsattList")
    @WebResult(name = "GetAnsattListResultMessage", targetNamespace = "http://ansattlist.bluegarden.no/service/v3_1", partName = "GetAnsattListResultMessage")
    public GetAnsattListResultMessageType getAnsattList(
            @WebParam(partName = "GetAnsattListRequestMessage", name = "GetAnsattListRequestMessage", targetNamespace = "http://ansattlist.bluegarden.no/service/v3_1")
                    GetAnsattListRequestMessageType getAnsattListRequestMessage,
            @WebParam(partName = "BSBHeader", name = "BSBHeader", targetNamespace = "http://bluemsg.bluegarden.no/object/v3", header = true)
                    BSBHeaderType bsbHeader
    );
}
